"""Markdown gaps-checklist formatter for ready scan results.

Generates a self-contained .md file with blocking/warning/exception/passing
sections and a summary table. Designed for committing alongside baselines
so the readiness state is human-readable in any markdown viewer.
"""

import datetime


def format_markdown(
    definitions: dict,
    results: list[dict],
    output_path: str,
    *,
    service_name: str = "",
    readiness_pct: float = 0.0,
    exceptions: list[dict] | None = None,
) -> str:
    """Return the full markdown string. The caller writes the file."""
    exceptions = exceptions or []
    exc_by_id = {e.get("checkpoint_id", ""): e for e in exceptions}

    blocking = [
        r for r in results
        if r.get("status") in ("fail", "expired_exception")
        and r.get("severity") == "red"
    ]
    warnings = [
        r for r in results
        if r.get("status") in ("fail", "expired_exception")
        and r.get("severity") == "yellow"
    ]
    exception_items = [r for r in results if r.get("status") == "exception"]
    passing_items = [r for r in results if r.get("status") == "pass"]
    skipped_items = [r for r in results if r.get("status") == "skip"]

    total = len(results)
    evaluated = total - len(skipped_items)
    passing_count = len(passing_items)

    # Sources line from checkpoint metadata
    metadata = definitions.get("metadata", {}) or {}
    source_name = metadata.get("guideline_name", "")
    if source_name:
        source_version = metadata.get("guideline_version", "")
        sources_line = source_name + (
            f" (v{source_version})" if source_version else ""
        )
    else:
        unique_guidelines: list[str] = []
        seen: set[str] = set()
        for cp in definitions.get("checkpoints", []):
            g = cp.get("guideline", "")
            if g and g not in seen:
                seen.add(g)
                unique_guidelines.append(g)
        sources_line = ", ".join(unique_guidelines) if unique_guidelines else "—"

    timestamp = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
        "%Y-%m-%d %H:%M:%S UTC"
    )

    lines: list[str] = []
    lines.append(f"# Gaps Checklist — {service_name}")
    lines.append("")
    lines.append(f"_Auto-generated by `ready scan --markdown` on {timestamp}_")
    lines.append("")
    lines.append(
        f"**Readiness: {readiness_pct:.0f}%** "
        f"({passing_count}/{evaluated} checks passing)"
    )
    lines.append("")
    lines.append(f"**Sources:** {sources_line}")
    lines.append("")

    def _render_gap(item: dict, icon: str) -> None:
        title = item.get("title", item.get("checkpoint_id", "unknown"))
        lines.append(f"### {icon} {title}")
        lines.append("")
        section = item.get("guideline_section", "")
        if section:
            lines.append(f"**Section:** {section}")
        check_type = item.get("type", "")
        if check_type:
            lines.append(f"**Type:** {check_type}")
        evidence = item.get("evidence") or []
        if evidence:
            joined = ", ".join(f"`{e}`" for e in evidence[:5])
            lines.append(f"**Evidence:** {joined}")
        message = item.get("message", "")
        if message:
            lines.append(f"**Details:** {message}")
        fix_hint = item.get("fix_hint", "")
        if fix_hint and fix_hint != title:
            lines.append(f"**Fix:** {fix_hint}")
        lines.append("")

    # Blocking
    lines.append(f"## ✗ Blocking ({len(blocking)})")
    lines.append("")
    if blocking:
        for item in blocking:
            _render_gap(item, "✗")
    else:
        lines.append("_None — no blocking issues._")
        lines.append("")

    # Warnings
    lines.append(f"## ⚠ Warnings ({len(warnings)})")
    lines.append("")
    if warnings:
        for item in warnings:
            _render_gap(item, "⚠")
    else:
        lines.append("_None._")
        lines.append("")

    # Exceptions
    lines.append(f"## Exceptions ({len(exception_items)})")
    lines.append("")
    if exception_items:
        for item in exception_items:
            title = item.get("title", item.get("checkpoint_id", "unknown"))
            lines.append(f"### {title}")
            lines.append("")
            exc = exc_by_id.get(item.get("checkpoint_id", ""), {})
            justification = exc.get("justification") or item.get("message", "")
            accepted_by = exc.get("accepted_by", "")
            expires = exc.get("expires", "")
            if justification:
                lines.append(f"**Justification:** {justification}")
            if accepted_by:
                lines.append(f"**Accepted by:** {accepted_by}")
            if expires:
                lines.append(f"**Expires:** {expires}")
            lines.append("")
    else:
        lines.append("_None._")
        lines.append("")

    # Passing — grouped by guideline_section
    lines.append(f"## ✓ Passing ({len(passing_items)})")
    lines.append("")
    if passing_items:
        grouped: dict[str, list[dict]] = {}
        for item in passing_items:
            section = item.get("guideline_section") or "Uncategorized"
            grouped.setdefault(section, []).append(item)
        for section in sorted(grouped.keys()):
            lines.append(f"### {section}")
            lines.append("")
            for item in grouped[section]:
                title = item.get("title", item.get("checkpoint_id", "unknown"))
                lines.append(f"- ~~{title}~~")
            lines.append("")
    else:
        lines.append("_No passing checks._")
        lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| ✗ Blocking | {len(blocking)} |")
    lines.append(f"| ⚠ Warning | {len(warnings)} |")
    lines.append(f"| ✓ Passing | {len(passing_items)} |")
    lines.append(f"| Exceptions | {len(exception_items)} |")
    if skipped_items:
        lines.append(f"| Skipped (not applicable) | {len(skipped_items)} |")
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")

    return "\n".join(lines)
